### PR TITLE
Fixed search bug. Role was being searched by the regular expression rath...

### PR DESCRIPTION
**Pull request by ghost**
...er than by the role itself. This resulted in queries like ... WHERE role = "is:hacker" instead of the correct ... WHERE role = "hacker".

### CODE REVIEW

**Comment by ghost** [comment]
Found another bug. I also merged my branch that contained the tests for user search.

@jonahoffline  Check it out when you can. Especially the tests. Feedback is welcome.

I noticed this PR got a bit messy. Close it. I'll clean it up and re-submit.

**Comment by jonahoffline** [comment]
@crzrcn I'll close it now, so you can resubmit. 
When you do, try adding files manually instead of a `git add .` or `git commit -am` so we stop dragging files like `database.yml` Thanks :+1:

**Comment by jonahoffline** [comment]
@crzrcn I'll checkout your fork while you resubmit.

**Comment by ghost** [comment]
@jonahoffline I'll be on IRC, while I re-submit if you got any feedback.

**Pull request closed without merging**
