### PR TITLE
User search testing and updates

### LINKED ISSUE #23: Search bug.
Role is being searched by the regular expression rather than by the role itself. This results in queries like ... WHERE role = "is:hacker" instead of the correct ... WHERE role = "hacker".

### PR DESCRIPTION
**Pull request by ghost**
This fixes #23 and adds testing.

### CODE REVIEW

**Comment by jonahoffline** [comment]
@crzrcn To fix this mofo, run this:
`./bin/rails g migration AddUnaccentPgsqlExtension`

Then copy paste this migration I made:
https://gist.github.com/jonahoffline/6706882

**Comment by jonahoffline** [comment]
Fawk, I'll try to find a workaround for this later Tonight.

**Comment by ghost** [comment]
Man, I give up. Fuck Travis.

**Comment by jpadilla** [comment]
Guys, decided to do `reset --hard` on master. There's a branch called dev that has master's original content including this PR. Decided to do so because I saw this wasn't that stable and didn't want the project to be on hold. @r23712 has been working on something that we could launch soon. From now on let's try to keep the master branch always deployable. We can work on new things in feature branches and merge them once their "stable".

Any thoughts or feedback on this? Anyone have a good workflow we should be using to keep things sane?

**Comment by ghost** [comment]
Good idea.

**Comment by jpadilla** [comment]
Moved this again from dev branch to search branch.

**Comment by jonahoffline** [comment]
Closing this issue as the search feature was removed.

**Pull request closed without merging**
