### PR TITLE
Added search users by roles (e.g. 'is:hacker', 'is:forhire is:hacker') a...

### PR DESCRIPTION
**Pull request by ghost**
...nd full text search on the user's bio by keywords (e.g. 'python backend developer'). Search by roles and keywords is also possible (e.g. 'is:hacker is:forhire python'). In order to test full text search on dev you need to connect to a PostgreSQL database.

### CODE REVIEW

**Comment by jpadilla** [comment]
This is great! Hopefully I'll get a chance to check it out more closely tomorrow. @jonahoffline you should check it out too when you can.

**Comment by jonahoffline** [comment]
@crazirican Thanks for your contribution. 

@jpadilla I'll check it out when I get home.

**Comment by jonahoffline** [comment]
@crazirican There are some conflicts with your commits :sob: so I'm going to have to resolve them manually before merging :sweat: 

I'll start working on this now! :neckbeard:

**Comment by jonahoffline** [comment]
@jpadilla Once I merge this, the rest of the team will have to switch from Sqlite to PostgreSQL in development.
[PostgresApp](http://postgresapp.com) FTW!

**Comment by jpadilla** [comment]
@jonahoffline @crazirican whenever you've got a chance update the README file with any instructions for setting up the current development environment with PostgreSQL

**Comment by jonahoffline** [comment]
@jpadilla I'm at it, I'm refactoring some parts to optimize the search.

**Comment by ryanoliver** [comment]
@crazirican remember to update the README file like @jpadilla said.

cc @jonahoffline

**Pull request merged**
