### PR TITLE
Security fix

### PR DESCRIPTION
**Pull request by jonahoffline**
Hey guys, this is a small security change for the project. Having the secret_key public puts any deployed instance of this project on risk. To generate a new key, just run:

$ rake secret

Add the new key to a new environment variable named **SECRET_TOKEN**
If using heroku:

heroku config:set **SECRET_KEY**=new_key_here

In case the env. var isn't defined in the system, it will fallback to the previous one so that anyone contributing to the project don't have to generate a new key every time they do a fork. Cheers!

### CODE REVIEW

**Comment by jpadilla** [comment]
Thanks dude! What do you think about the project? We only have a few more things to get done to put it out there so people can start using it and giving us feedback.

**Comment by jonahoffline** [comment]
I'm very excited about this, It looks awesome! I wish I had known this about this sooner so I could contribute more. If there is anything else that still needs to get implemented let me know. Btw, I'm currently refactoring the user view so we can remove logic from there (for the social icons), I'll send a pull when it's done :)

**Comment by jpadilla** [comment]
Awesome! We have a project on Blimp. Just sent you an invite. It'd definitely be awesome if you could give us a hand.

**Comment by jonahoffline** [comment]
Awesome :)

**Pull request merged**
